### PR TITLE
Fix broken security blackbox tests.

### LINKED ISSUE #380: Broken security tests
# Bug

```
Info:System-Management Test Completed.
.FileNotFoundError: [Errno 2] No such file or directory: './docker-compose-nexus.yml'
cat: can't open '/vault/config/assets/resp-init.json': No such file or directory
Info:Securityservice Setup Completed.
Info: Initiating Securityservice Test.
```

Additional details:
```
$ cat bin/setupSecurityserviceTest.sh 
#!/bin/bash

OT=$(docker-compose -f $(ls ../ | awk '/docker-compose/ && !/test-tools/') run edgex-proxy --init=false --useradd=jerry --group=admin | tail -1)
export TOKEN=$( echo $OT | sed 's/.*: \([^.]*\).*/\1/')

#echo $TOKEN

RT=$(docker exec -i edgex-vault sh -c "cat /vault/config/assets/resp-init.json")
export ROOTKEY=$(echo $RT | sed 's/.*"\(.*\)"[^"]*$/\1/')

#echo $ROOTKEY

echo "Info:Securityservice Setup Completed."
```

- Remove dependency on /vault/config/assets/resp-init.json
- See https://github.com/edgexfoundry/edgex-go/issues/2267 for corrected usage of edgex-proxy to create a user

Corresponding usage in `bin/runSecurityserviceTest.sh`
```
docker-compose -f ../docker-compose-test-tools.yml run --rm postman run ${COLLECTION_PATH} \
    --environment=${ENV_PATH} --insecure --reporters="junit,cli" --global-var accessToken=$TOKEN --global-var rootKey=$ROOTKEY
```

### PR DESCRIPTION
**Pull request by bnevis-i**
Bring blackbox tests up-to-date to fix several broken issues:
- Attempting to create Kong user with wrong path to compose file
- Adapt creation of Kong user to override entrypoint in compose file
- Vault root token no longer exists
- Calling wrong Vault API to check for token validity
- Improperly passing environment variable from setupSecurityServiceTest.sh
  to runSecurityServiceTest.sh

Fixed #380 

Signed-off-by: Bryon Nevis <bryon.nevis@intel.com>

cc: @tingyuz , @jim-wang-intel , @cloudxxx8 , @jinlinGuan

### CODE REVIEW

File: bin/run.sh [hunk 1]
```diff
@@ -33,7 +33,7 @@ APPSERVICECONFIGURABLELOGSPATH=$BASEPATH/appserviceconfigurable$TIMESTAMPFORMAT.
 EDGEXLOGSPATH=$BASEPATH/edgex$TIMESTAMPFORMAT.log
 
 securityTest() {
-	$(dirname "$0")/setupSecurityserviceTest.sh
+	. $(dirname "$0")/setupSecurityserviceTest.sh
```
Comment (cloudxxx8) [inline bin/run.sh:36]: why do we need the dot here?

Comment (bnevis-i) [reply bin/run.sh:36]: At some point, code to set the Kong token and Vault token was moved from runSecurity to setupSecurity.  Without the dot ("source") the environment variable will die in the subshell and won't be passed to the runSecurity script.  Basically, all of these tests have been running with invalid Kong/Vault tokens for quite some time.

File: bin/postman-test/collections/security-service.postman_collection.json [hunk 2]
```diff
@@ -62,69 +62,13 @@
 					},
 					"response": []
 				},
-				{
```
Comment (bnevis-i) [inline bin/postman-test/collections/security-service.postman_collection.json:65]: This test is useless, we already check sys/health which aggregates all of this.

File: bin/postman-test/collections/security-service.postman_collection.json [hunk 3]
```diff
@@ -160,16 +105,17 @@
 							}
 						],
 						"url": {
-							"raw": "https://localhost:8200/v1/sys/key-status",
+							"raw": "https://localhost:8200/v1/auth/token/lookup-self",
```
Comment (bnevis-i) [inline bin/postman-test/collections/security-service.postman_collection.json:108]: key-status is a check on the vault encryption key.  What was intended was a check on the vault token validity.  Repeated numerous places.

File: bin/setupSecurityserviceTest.sh [hunk 4]
```diff
@@ -1,14 +1,14 @@
...
+OT=$(docker-compose -f ../$(ls ../ | awk '/docker-compose/ && !/test-tools/') run --rm --entrypoint /edgex/security-proxy-setup edgex-proxy --init=false --useradd=jerry --group=admin | tail -1)
 export TOKEN=$( echo $OT | sed 's/.*: \([^.]*\).*/\1/')
 
-#echo $TOKEN
+#echo TOKEN=$TOKEN
 
-RT=$(docker exec -i edgex-vault sh -c "cat /vault/config/assets/resp-init.json")
-export ROOTKEY=$(echo $RT | sed 's/.*"\(.*\)"[^"]*$/\1/')
+RT=$(docker exec -i edgex-vault-worker sh -c "cat /tmp/edgex/secrets/edgex-security-proxy-setup/secrets-token.json")
+export VAULTKEY=$(echo $RT | sed 's/.*"client_token":"\([^"]*\)".*/\1/')
```
Comment (bnevis-i) [inline bin/setupSecurityserviceTest.sh:9]: Variable rename is just to put emphasis on the fact that the root token is deprecated.

**Review by cloudxxx8 — APPROVED** [review]
LGTM
we've verified locally
